-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 23:18:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema distributed_encryption
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `distributed_encryption` ;

-- -----------------------------------------------------
-- Schema distributed_encryption
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `distributed_encryption` DEFAULT CHARACTER SET utf8mb4 ;
USE `distributed_encryption` ;

-- -----------------------------------------------------
-- Table `distributed_encryption`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distributed_encryption`.`t_user` ;

CREATE TABLE IF NOT EXISTS `distributed_encryption`.`t_user` (
  `id_user` VARCHAR(32) NOT NULL,
  `pass_user` VARCHAR(32) NOT NULL,
  `nama_user` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  `last_login_user` DATETIME NULL,
  `type_of_user` VARCHAR(10) NOT NULL,
  `disabled_user` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distributed_encryption`.`t_user_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distributed_encryption`.`t_user_key` ;

CREATE TABLE IF NOT EXISTS `distributed_encryption`.`t_user_key` (
  `id_user_key` VARCHAR(32) NOT NULL,
  `name_user_key` VARCHAR(45) NOT NULL,
  `gen_date_user_key` DATETIME NOT NULL,
  `t_user_id_user` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_user_key`),
  INDEX `fk_t_user_key_t_user1_idx` (`t_user_id_user` ASC),
  CONSTRAINT `fk_t_user_key_t_user1`
    FOREIGN KEY (`t_user_id_user`)
    REFERENCES `distributed_encryption`.`t_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distributed_encryption`.`t_user_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distributed_encryption`.`t_user_files` ;

CREATE TABLE IF NOT EXISTS `distributed_encryption`.`t_user_files` (
  `id_user_files` VARCHAR(32) NOT NULL,
  `orig_name_user_files` VARCHAR(100) NOT NULL,
  `saved_name_user_files` VARCHAR(32) NOT NULL,
  `status_user_files` VARCHAR(10) NOT NULL DEFAULT 'RAW',
  `date_up_user_files` DATETIME NOT NULL,
  `t_user_id_user` VARCHAR(32) NOT NULL,
  `t_user_key_id_user_key` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_user_files`),
  INDEX `fk_t_user_files_t_user1_idx` (`t_user_id_user` ASC),
  INDEX `fk_t_user_files_t_user_key1_idx` (`t_user_key_id_user_key` ASC),
  CONSTRAINT `fk_t_user_files_t_user1`
    FOREIGN KEY (`t_user_id_user`)
    REFERENCES `distributed_encryption`.`t_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_files_t_user_key1`
    FOREIGN KEY (`t_user_key_id_user_key`)
    REFERENCES `distributed_encryption`.`t_user_key` (`id_user_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distributed_encryption`.`t_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `distributed_encryption`.`t_jobs` ;

CREATE TABLE IF NOT EXISTS `distributed_encryption`.`t_jobs` (
  `id_jobs` INT NOT NULL AUTO_INCREMENT,
  `date_enter_jobs` DATETIME NOT NULL,
  `date_start_jobs` DATETIME NULL,
  `date_finish_jobs` DATETIME NULL,
  `type_of_jobs` TINYINT NOT NULL,
  `t_user_files_id_user_files` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_jobs`, `t_user_files_id_user_files`),
  INDEX `fk_t_jobs_t_user_files1_idx` (`t_user_files_id_user_files` ASC),
  CONSTRAINT `fk_t_jobs_t_user_files1`
    FOREIGN KEY (`t_user_files_id_user_files`)
    REFERENCES `distributed_encryption`.`t_user_files` (`id_user_files`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
